const adminData = {
  title: "Admin Portal",
  adminUsers: [
    { id: 1, name: "John Smith", role: "Super Admin", avatar: "/placeholder.svg?height=32&width=32" },
    { id: 2, name: "Sarah Johnson", role: "Admin", avatar: "/placeholder.svg?height=32&width=32" },
    { id: 3, name: "Michael Brown", role: "Support", avatar: "/placeholder.svg?height=32&width=32" },
  ],
  navigation: [
    { id: "dashboard", label: "Dashboard", icon: "BarChart3" },
    { id: "companies", label: "Companies", icon: "Building2" },
    { id: "products", label: "Products", icon: "Package" },
    { id: "orders", label: "Orders", icon: "ShoppingBag" },
    { id: "users", label: "Users", icon: "Users" },
    { id: "settings", label: "Settings", icon: "Settings" },
  ],
  companies: [
    {
      id: "company1",
      name: "ElectroShop",
      logo: "/placeholder.svg?height=40&width=40",
      industry: "Electronics",
      status: "active",
      stats: {
        revenue: 548220,
        orders: 12840,
        customers: 5240,
      },
      products: [
        {
          id: 1,
          name: "iPhone 14 Pro",
          category: "Electronics",
          price: 999,
          stock: 234,
          sales: 85,
          image: "/placeholder.svg?height=80&width=80",
        },
        {
          id: 2,
          name: "MacBook Air M2",
          category: "Electronics",
          price: 1199,
          stock: 122,
          sales: 57,
          image: "/placeholder.svg?height=80&width=80",
        },
        {
          id: 3,
          name: "Sony WH-1000XM5",
          category: "Electronics",
          price: 349,
          stock: 178,
          sales: 62,
          image: "/placeholder.svg?height=80&width=80",
        },
      ],
    },
    {
      id: "company2",
      name: "FashionHub",
      logo: "/placeholder.svg?height=40&width=40",
      industry: "Apparel",
      status: "active",
      stats: {
        revenue: 423150,
        orders: 9870,
        customers: 4120,
      },
      products: [
        {
          id: 1,
          name: "Designer T-Shirt",
          category: "Clothing",
          price: 49,
          stock: 432,
          sales: 76,
          image: "/placeholder.svg?height=80&width=80",
        },
        {
          id: 2,
          name: "Premium Jeans",
          category: "Clothing",
          price: 89,
          stock: 267,
          sales: 82,
          image: "/placeholder.svg?height=80&width=80",
        },
      ],
    },
    {
      id: "company3",
      name: "SportyGear",
      logo: "/placeholder.svg?height=40&width=40",
      industry: "Sports",
      status: "active",
      stats: {
        revenue: 312680,
        orders: 7450,
        customers: 3280,
      },
      products: [
        {
          id: 1,
          name: "Running Shoes",
          category: "Footwear",
          price: 129,
          stock: 345,
          sales: 94,
          image: "/placeholder.svg?height=80&width=80",
        },
        {
          id: 2,
          name: "Fitness Tracker",
          category: "Electronics",
          price: 89,
          stock: 178,
          sales: 62,
          image: "/placeholder.svg?height=80&width=80",
        },
      ],
    },
    {
      id: "company4",
      name: "HomeDecor",
      logo: "/placeholder.svg?height=40&width=40",
      industry: "Home & Living",
      status: "inactive",
      stats: {
        revenue: 198420,
        orders: 4320,
        customers: 2150,
      },
      products: [
        {
          id: 1,
          name: "Modern Lamp",
          category: "Furniture",
          price: 79,
          stock: 124,
          sales: 38,
          image: "/placeholder.svg?height=80&width=80",
        },
        {
          id: 2,
          name: "Throw Pillows",
          category: "Accessories",
          price: 29,
          stock: 210,
          sales: 45,
          image: "/placeholder.svg?height=80&width=80",
        },
      ],
    },
  ],
  revenueByMonth: [
    { month: "Jan", revenue: 65000, profit: 25000 },
    { month: "Feb", revenue: 59000, profit: 22000 },
    { month: "Mar", revenue: 80000, profit: 32000 },
    { month: "Apr", revenue: 81000, profit: 31000 },
    { month: "May", revenue: 56000, profit: 21000 },
    { month: "Jun", revenue: 55000, profit: 19000 },
    { month: "Jul", revenue: 40000, profit: 15000 },
    { month: "Aug", revenue: 72000, profit: 28000 },
    { month: "Sep", revenue: 96000, profit: 38000 },
  ],
  salesByCategory: [
    { name: "Electronics", value: 42 },
    { name: "Clothing", value: 28 },
    { name: "Footwear", value: 18 },
    { name: "Accessories", value: 12 },
  ],
  chartColors: ["#4f46e5", "#0ea5e9", "#10b981", "#f59e0b"],
  statCards: [
    {
      id: "revenue",
      title: "Total Revenue",
      icon: "DollarSign",
      iconBg: "bg-primary/10",
      iconColor: "text-primary",
      trend: "+12.5%",
      trendDirection: "up",
    },
    {
      id: "orders",
      title: "Total Orders",
      icon: "ShoppingBag",
      iconBg: "bg-green-100",
      iconColor: "text-green-600",
      trend: "+8.2%",
      trendDirection: "up",
    },
    {
      id: "customers",
      title: "Total Customers",
      icon: "Users",
      iconBg: "bg-purple-100",
      iconColor: "text-purple-600",
      trend: "+4.7%",
      trendDirection: "up",
    },
    {
      id: "products",
      title: "Total Products",
      icon: "Layers",
      iconBg: "bg-amber-100",
      iconColor: "text-amber-600",
      trend: "-1.5%",
      trendDirection: "down",
    },
  ],
  timeRanges: [
    { value: "week", label: "Last Week" },
    { value: "month", label: "Last Month" },
    { value: "quarter", label: "Last Quarter" },
    { value: "year", label: "Last Year" },
  ],
  selectorData: {
    emptyMessage: "No company found.",
    searchPlaceholder: "Search company...",
  },
};

export default adminData;